### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by adriaangraas** [cicwi/software-guidelines#1]
Hi,

First of all, super nice to have a guide. As a group I think we should! As a way for this repo to get some momentum: here are my thoughts about the software-release guide, that I'd like to share (open for discussion).

- We should separate concerns of the guide a bit more. The guide is a motivation, check-list, programmer guide at the same time, and I find it sometimes a bit text-heavy.
- Identify the goals of the guide. I think the guide should serve as
  - a how-to specific to releasing scientific software, and pursuing Open Science;
  - a reference to useful software tools in the field of CI;
  - a (weak) group consensus of a release: which licenses, lay-out READMEs, etc.;
  - references to good software guides for novice programmers in some languages;
 - I think we should try to stay away from explaining software details. Those things get outdated to easily, and there is really no end to things that can be explained. Instead we should just highlight important concepts and provide references. Maybe we should put together some links to semantic versioning, PEPs, best practices, howtos into Conda. Especially those that will help us write code in the context of CI: managing CUDA dependencies and working with ASTRA.

I realize this all is more easily said than done, but maybe some fruitful discussions will come from here.

Ah, and lastly I stumbled upon https://github.com/thi-ng/org-spec which is a nice HTML-template, that makes the guide a bit more easily to digest. What do you think about this?

**Comment by jwbuurlage** [comment]
Thanks Adriaan for your comments! Let me try to explain our reasoning (also open for discussion, of course).

> We should separate concerns of the guide a bit more. The guide is a motivation, check-list, programmer guide at the same time, and I find it sometimes a bit text-heavy.

The rationale for setting it up this way is that you can't have one without the other.

- If you don't have a _motivation_, readers may wonder why to do it at all.
- If you don't have a _programmer guide_, readers may be convinced that they should share their software, and know what constitutes a software package, but still do not now how to  do it in practice.
- If you don't have a _checklist_, you lack an easy way to remind yourself what to do when e.g. distributing a new release (while now you can just look at the 'further development section, and follow the checklist). 

> Identify the goals of the guide. 

For me, the software guide is supposed to be two of the things you mention: a how-to for releasing software, and a consensus of what a release is. In my opinion references to useful tools, or guides for novice programmers make more sense for the other guide (the more general collection of how-tos).

> I think we should try to stay away from explaining software details

I feel that what we write in the first sections (before 'putting theory to practice') is pretty much independent of technology changes. We can update the practical section as technology changes, it is supposed to be a living document.

I think what you say is true, we should have a collection of links, best practices, etc. -- but not as part of the release guide. Rather, this belongs to the more general collection of how-tos. 

> Ah, and lastly I stumbled upon https://github.com/thi-ng/org-spec which is a nice HTML-template, that makes the guide a bit more easily to digest. What do you think about this?

Yeah! If you can set that up that would be great :) The output now is just the default HTML export.

**Comment by adriaangraas** [comment]
Thanks for your quick reply, I think it is a good to discuss this a bit!

I agree that we need all of these things (motivation, programmer guide and checklist). As an introductory read, the release guide is great as is. However, as an already motivated reader I find it difficult to extract an overview of what I could/should do, and where to find everything in the read. I think that in the end I want to come back to the guide and see if my project checks all the boxes. Personally, I'm most interested to find out what good principles are, less in project conversion/set-up details.

My gut feeling is that users will come to this repository for two reasons: to see if their code is up to standards, and to find help and inspiration in tooling and the releasing process. If it is to long of a read, the core principles might go lost in the details.

What about having something like a shortlist that with concepts that people could jump into (perhaps linking to sections in the guide). More like a manifest: "these points are what we collectively think are good ideas, and here is where you can go to find out how"?

I agree with you on putting technical details in a separate guide.

I'll try to make the template working!

**Comment by jwbuurlage** [comment]
> What about having something like a shortlist that with concepts that people could jump into (perhaps linking to sections in the guide). More like a manifest: "these points are what we collectively think are good ideas, and here is where you can go to find out how"?

An 'at-a-glance' overview would be very useful. I think it would be good to have this as a separate section! The 'find out how' is basically (maybe an extended version of) the document we have written now.

**Comment by jwbuurlage** [comment]
Closing this. I still think the checklist is a good idea, if you want to write it :)

**Comment by ahendriksen** [comment]
There is also a checklist in the cookiecutter template, see https://github.com/ahendriksen/cone_balls/blob/6beed0f5fd8d68f5ea032529fb04d85efc509a7d/README.md
