### ISSUE TITLE
Renaming the repository

### ISSUE THREAD

**Issue by jwbuurlage** [cicwi/software-guidelines#8]
I would like to propose to rename the repository from `software-guidelines` to `software-guides`. 

- Guidelines sounds more like rules, instead of help
- The how-to guide has nothing to do with a 'guideline',  (although the release guide can be seen as guidelines for released software)
- It reflects the title in the README

**Comment by adriaangraas** [comment]
Absolutely, agreed.
(Especially third point.)

**Comment by wjp** [comment]
That does match the content and goals better, yes. Good idea.

**Comment by ahendriksen** [comment]
Agreed
